/**
 * Generated by Apache Royale Compiler from de/mayflower/royaleMvp/base/Preloader.as
 * de.mayflower.royaleMvp.base.Preloader
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('de.mayflower.royaleMvp.base.Preloader');
/* Royale Dependency List: de.mayflower.royaleMvp.base.App,de.mayflower.royaleMvp.base.Setting,de.mayflower.royaleMvp.ui.UIComponentFacility,mx.controls.Image,mx.core.UIComponent*/




/**
 * @constructor
 */
de.mayflower.royaleMvp.base.Preloader = function() {
};


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('de.mayflower.royaleMvp.base.Preloader', de.mayflower.royaleMvp.base.Preloader);


/**
 * @private
 * @type {mx.controls.Image}
 */
de.mayflower.royaleMvp.base.Preloader.prototype.de_mayflower_royaleMvp_base_Preloader_preloaderLogo = null;


/**
 * @private
 * @type {mx.core.UIComponent}
 */
de.mayflower.royaleMvp.base.Preloader.prototype.de_mayflower_royaleMvp_base_Preloader_preloaderBg = null;


/**
 * @private
 * @type {mx.core.UIComponent}
 */
de.mayflower.royaleMvp.base.Preloader.prototype.de_mayflower_royaleMvp_base_Preloader_preloaderFg = null;


/***************************************************************************************************************
 *   Sets up the preloader with the loaded preloader images.
 *
 *   @asparam logoImage The preloader logo image.
 * @export
 * @param {mx.controls.Image} logoImage
 */
de.mayflower.royaleMvp.base.Preloader.prototype.setupPreloader = function(logoImage) {
  this.de_mayflower_royaleMvp_base_Preloader_preloaderLogo = logoImage;
  var /** @type {number} */ logoX = ((de.mayflower.royaleMvp.base.Setting.SCREEN_WIDTH - this.de_mayflower_royaleMvp_base_Preloader_preloaderLogo.width) / 2);
  var /** @type {number} */ logoY = ((de.mayflower.royaleMvp.base.Setting.SCREEN_HEIGHT - this.de_mayflower_royaleMvp_base_Preloader_preloaderLogo.height - de.mayflower.royaleMvp.base.Setting.OFFSET_PRELOADER_DISTANCE_Y - de.mayflower.royaleMvp.base.Setting.OFFSET_PRELOADER_BAR_HEIGHT) / 2);
  this.de_mayflower_royaleMvp_base_Preloader_preloaderLogo.visible = true;
  this.de_mayflower_royaleMvp_base_Preloader_preloaderLogo.setStyle("opacity", "0.0");
  this.de_mayflower_royaleMvp_base_Preloader_preloaderLogo.x = logoX;
  this.de_mayflower_royaleMvp_base_Preloader_preloaderLogo.y = logoY;
  this.de_mayflower_royaleMvp_base_Preloader_preloaderBg = de.mayflower.royaleMvp.ui.UIComponentFacility.createFilledRect((this.de_mayflower_royaleMvp_base_Preloader_preloaderLogo.width + "px"), (de.mayflower.royaleMvp.base.Setting.OFFSET_PRELOADER_BAR_HEIGHT + "px"), de.mayflower.royaleMvp.base.Setting.COLOR_PRELOADER_BG);
  this.de_mayflower_royaleMvp_base_Preloader_preloaderBg.x = logoX;
  this.de_mayflower_royaleMvp_base_Preloader_preloaderBg.y = (logoY + this.de_mayflower_royaleMvp_base_Preloader_preloaderLogo.height + de.mayflower.royaleMvp.base.Setting.OFFSET_PRELOADER_DISTANCE_Y);
  this.de_mayflower_royaleMvp_base_Preloader_preloaderBg.setStyle("opacity", "0.0");
  this.de_mayflower_royaleMvp_base_Preloader_preloaderFg = de.mayflower.royaleMvp.ui.UIComponentFacility.createFilledRect("0px", (de.mayflower.royaleMvp.base.Setting.OFFSET_PRELOADER_BAR_HEIGHT + "px"), de.mayflower.royaleMvp.base.Setting.COLOR_PRELOADER_FG);
  this.de_mayflower_royaleMvp_base_Preloader_preloaderFg.x = logoX;
  this.de_mayflower_royaleMvp_base_Preloader_preloaderFg.y = (logoY + this.de_mayflower_royaleMvp_base_Preloader_preloaderLogo.height + de.mayflower.royaleMvp.base.Setting.OFFSET_PRELOADER_DISTANCE_Y);
  this.de_mayflower_royaleMvp_base_Preloader_preloaderFg.setStyle("opacity", "1.0");
};


/***************************************************************************************************************
 *   Sets the preloading progress to the specified percent.
 *
 *   @asparam percent A floating value from 0.0 to 1.0.
 * @export
 * @param {number} percent
 */
de.mayflower.royaleMvp.base.Preloader.prototype.setPreloaderPercent = function(percent) {
  this.de_mayflower_royaleMvp_base_Preloader_preloaderFg.setStyle("width", (this.de_mayflower_royaleMvp_base_Preloader_preloaderLogo.width * percent) + "px");
};


/***************************************************************************************************************
 *   Adds the preloader bg and fg to the specified component.
 *
 *   @asparam component The component to add the preloader bg and fg to.
 * @export
 * @param {mx.core.UIComponent} component
 */
de.mayflower.royaleMvp.base.Preloader.prototype.addTo = function(component) {
  de.mayflower.royaleMvp.base.App.addElement(component, this.de_mayflower_royaleMvp_base_Preloader_preloaderBg);
  de.mayflower.royaleMvp.base.App.addElement(component, this.de_mayflower_royaleMvp_base_Preloader_preloaderFg);
};


/***************************************************************************************************************
 *   Sets the opacity for all elements of the preloader.
 *
 *   @asparam opacity The opacity value as a string to set.
 * @export
 * @param {string} opacity
 */
de.mayflower.royaleMvp.base.Preloader.prototype.setOpacity = function(opacity) {
  this.de_mayflower_royaleMvp_base_Preloader_preloaderLogo.setStyle("opacity", opacity);
  this.de_mayflower_royaleMvp_base_Preloader_preloaderFg.setStyle("opacity", opacity);
  this.de_mayflower_royaleMvp_base_Preloader_preloaderBg.setStyle("opacity", opacity);
};


/***************************************************************************************************************
 *   Completes the preloader by setting the full width for the preloader fg.
 *   Additionally hides the preloader bg.
 * @export
 */
de.mayflower.royaleMvp.base.Preloader.prototype.setPreloadingComplete = function() {
  this.de_mayflower_royaleMvp_base_Preloader_preloaderFg.setStyle("width", String(this.de_mayflower_royaleMvp_base_Preloader_preloaderLogo.width) + "px");
  this.de_mayflower_royaleMvp_base_Preloader_preloaderBg.setStyle("opacity", "0.0");
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
de.mayflower.royaleMvp.base.Preloader.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'Preloader', qName: 'de.mayflower.royaleMvp.base.Preloader', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
de.mayflower.royaleMvp.base.Preloader.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {return {};},
    methods: function () {
      return {
        'setupPreloader': { type: 'void', declaredBy: 'de.mayflower.royaleMvp.base.Preloader', parameters: function () { return [ { index: 1, type: 'mx.controls.Image', optional: false } ]; }},
        'setPreloaderPercent': { type: 'void', declaredBy: 'de.mayflower.royaleMvp.base.Preloader', parameters: function () { return [ { index: 1, type: 'Number', optional: false } ]; }},
        'addTo': { type: 'void', declaredBy: 'de.mayflower.royaleMvp.base.Preloader', parameters: function () { return [ { index: 1, type: 'mx.core.UIComponent', optional: false } ]; }},
        'setOpacity': { type: 'void', declaredBy: 'de.mayflower.royaleMvp.base.Preloader', parameters: function () { return [ { index: 1, type: 'String', optional: false } ]; }},
        'setPreloadingComplete': { type: 'void', declaredBy: 'de.mayflower.royaleMvp.base.Preloader'}
      };
    }
  };
};
/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.Preloader.prototype.ROYALE_REFLECTION_INFO.compileFlags = 9;

//# sourceMappingURL=./Preloader.js.map
