/**
 * Generated by Apache Royale Compiler from de/mayflower/royaleMvp/base/Setting.as
 * de.mayflower.royaleMvp.base.Setting
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('de.mayflower.royaleMvp.base.Setting');
/* Royale Dependency List: */



/**
 * @constructor
 */
de.mayflower.royaleMvp.base.Setting = function() {
};


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('de.mayflower.royaleMvp.base.Setting', de.mayflower.royaleMvp.base.Setting);


/**
 * @export
 * @const
 * @type {boolean}
 */
de.mayflower.royaleMvp.base.Setting.DEBUG_MODE = true;


/**
 * @export
 * @const
 * @type {string}
 */
de.mayflower.royaleMvp.base.Setting.APP_TITLE = "Fotografie Martin Gehrig, FlashMartinAdobeRoyale v.1.0, MVP";


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.Setting.GAME_LOOP_DELAY = 16.6;


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.Setting.SCREEN_WIDTH = 1024;


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.Setting.SCREEN_HEIGHT = 636;


/**
 * @export
 * @const
 * @type {string}
 */
de.mayflower.royaleMvp.base.Setting.COLOR_SCREEN_BG = "#505050";


/**
 * @export
 * @const
 * @type {string}
 */
de.mayflower.royaleMvp.base.Setting.COLOR_BODY_BG = "#848484";


/**
 * @export
 * @const
 * @type {string}
 */
de.mayflower.royaleMvp.base.Setting.COLOR_PRELOADER_BG = "#6a6a6a";


/**
 * @export
 * @const
 * @type {string}
 */
de.mayflower.royaleMvp.base.Setting.COLOR_PRELOADER_FG = "#ffffff";


/**
 * @export
 * @const
 * @type {string}
 */
de.mayflower.royaleMvp.base.Setting.COLOR_SCROLL_LANE = "#5c5c5c";


/**
 * @export
 * @const
 * @type {string}
 */
de.mayflower.royaleMvp.base.Setting.COLOR_SCROLL_KNOB = "#ffffff";


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.Setting.TICKS_FADE_IN_OUT = 60;


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.Setting.TICKS_DELAY_AROUND_PRELOADING = 15;


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.Setting.OFFSET_PRELOADER_BAR_HEIGHT = 6;


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.Setting.OFFSET_PRELOADER_DISTANCE_Y = 18;


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.Setting.OFFSET_GALLERY_HEIGHT = 330;


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.Setting.OFFSET_GALLERY_IMAGES_Y = 150;


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.Setting.OFFSET_HEADER_LOGO_X = 75;


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.Setting.OFFSET_HEADER_LOGO_Y = 50;


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.Setting.OFFSET_SCROLL_KNOB_WIDTH = 75;


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.Setting.OFFSET_SCROLL_LANE_HEIGHT = 6;


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.Setting.OFFSET_GALLERY_SPEED_X = 1;


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
de.mayflower.royaleMvp.base.Setting.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'Setting', qName: 'de.mayflower.royaleMvp.base.Setting', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
de.mayflower.royaleMvp.base.Setting.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {return {};},
    methods: function () {return {};}
  };
};
/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.Setting.prototype.ROYALE_REFLECTION_INFO.compileFlags = 9;
/**
 * Provide reflection support for distinguishing dynamic fields on class object (static)
 * @export
 * @const
 * @type {Array<string>}
 */
de.mayflower.royaleMvp.base.Setting.prototype.ROYALE_REFLECTION_INFO.statics = Object.keys(de.mayflower.royaleMvp.base.Setting);

//# sourceMappingURL=./Setting.js.map
