/**
 * Generated by Apache Royale Compiler from de/mayflower/royaleMvp/base/State.as
 * de.mayflower.royaleMvp.base.State
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('de.mayflower.royaleMvp.base.State');
/* Royale Dependency List: */



/**
 * @constructor
 */
de.mayflower.royaleMvp.base.State = function() {
};


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('de.mayflower.royaleMvp.base.State', de.mayflower.royaleMvp.base.State);


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.State.LOAD_PRELOADER_IMAGES = 0;


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.State.DELAY_AFTER_STARTUP = 1;


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.State.FADE_IN_SCREEN_BG = 2;


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.State.FADE_IN_PRELOADER = 3;


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.State.DELAY_BEFORE_PRELOADING = 4;


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.State.LOAD_GALLERY_IMAGES = 5;


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.State.DELAY_AFTER_PRELOADING = 6;


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.State.FADE_OUT_PRELOADER = 7;


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.State.FADE_IN_SITE = 8;


/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.State.ANIMATE_SITE = 9;


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
de.mayflower.royaleMvp.base.State.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'State', qName: 'de.mayflower.royaleMvp.base.State', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
de.mayflower.royaleMvp.base.State.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {return {};},
    methods: function () {return {};}
  };
};
/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.State.prototype.ROYALE_REFLECTION_INFO.compileFlags = 9;
/**
 * Provide reflection support for distinguishing dynamic fields on class object (static)
 * @export
 * @const
 * @type {Array<string>}
 */
de.mayflower.royaleMvp.base.State.prototype.ROYALE_REFLECTION_INFO.statics = Object.keys(de.mayflower.royaleMvp.base.State);

//# sourceMappingURL=./State.js.map
