/**
 * Generated by Apache Royale Compiler from de/mayflower/royaleMvp/base/Website.as
 * de.mayflower.royaleMvp.base.Website
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('de.mayflower.royaleMvp.base.Website');
/* Royale Dependency List: de.mayflower.royaleMvp.base.App,de.mayflower.royaleMvp.base.Setting,de.mayflower.royaleMvp.ui.UIComponentFacility,mx.controls.Image,mx.core.UIComponent*/




/**
 * @constructor
 */
de.mayflower.royaleMvp.base.Website = function() {
};


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('de.mayflower.royaleMvp.base.Website', de.mayflower.royaleMvp.base.Website);


/**
 * @private
 * @type {mx.core.UIComponent}
 */
de.mayflower.royaleMvp.base.Website.prototype.de_mayflower_royaleMvp_base_Website_bgBody = null;


/**
 * @private
 * @type {mx.core.UIComponent}
 */
de.mayflower.royaleMvp.base.Website.prototype.de_mayflower_royaleMvp_base_Website_bgScreen = null;


/**
 * @private
 * @type {Array}
 */
de.mayflower.royaleMvp.base.Website.prototype.de_mayflower_royaleMvp_base_Website_galleryImages = null;


/**
 * @private
 * @type {number}
 */
de.mayflower.royaleMvp.base.Website.prototype.de_mayflower_royaleMvp_base_Website_galleryAnimationX = 0;


/**
 * @private
 * @type {number}
 */
de.mayflower.royaleMvp.base.Website.prototype.de_mayflower_royaleMvp_base_Website_galleryTotalWidth = 0;


/**
 * @private
 * @type {mx.controls.Image}
 */
de.mayflower.royaleMvp.base.Website.prototype.de_mayflower_royaleMvp_base_Website_menuPlaceholder = null;


/**
 * @private
 * @type {mx.controls.Image}
 */
de.mayflower.royaleMvp.base.Website.prototype.de_mayflower_royaleMvp_base_Website_headerLogo = null;


/**
 * @private
 * @type {mx.core.UIComponent}
 */
de.mayflower.royaleMvp.base.Website.prototype.de_mayflower_royaleMvp_base_Website_scrollLane = null;


/**
 * @private
 * @type {mx.core.UIComponent}
 */
de.mayflower.royaleMvp.base.Website.prototype.de_mayflower_royaleMvp_base_Website_scrollKnob = null;


/***************************************************************************************************************
 *   Creates the 'body' component which is an entire html body size container.
 * @export
 * @param {*} app
 */
de.mayflower.royaleMvp.base.Website.prototype.createBgBody = function(app) {
  this.de_mayflower_royaleMvp_base_Website_bgBody = de.mayflower.royaleMvp.ui.UIComponentFacility.createFilledRect("100%", "100%", "transparent");
  de.mayflower.royaleMvp.base.App.addElement(app, this.de_mayflower_royaleMvp_base_Website_bgBody);
};


/***************************************************************************************************************
 *   Creates the 'screen' component which is the actual website's background frame.
 * @export
 */
de.mayflower.royaleMvp.base.Website.prototype.createBgScreen = function() {
  this.de_mayflower_royaleMvp_base_Website_bgScreen = de.mayflower.royaleMvp.ui.UIComponentFacility.createFilledRect((de.mayflower.royaleMvp.base.Setting.SCREEN_WIDTH + "px"), (de.mayflower.royaleMvp.base.Setting.SCREEN_HEIGHT + "px"), de.mayflower.royaleMvp.base.Setting.COLOR_SCREEN_BG);
  this.de_mayflower_royaleMvp_base_Website_bgScreen.setStyle("opacity", "0.0");
  this.de_mayflower_royaleMvp_base_Website_bgScreen.setStyle("overflow", "hidden");
  de.mayflower.royaleMvp.base.App.addElement(this.de_mayflower_royaleMvp_base_Website_bgBody, this.de_mayflower_royaleMvp_base_Website_bgScreen);
};


/***************************************************************************************************************
 *   Horizontally and vertically centers the screen UIComponent inside the body UIComponent.
 * @export
 */
de.mayflower.royaleMvp.base.Website.prototype.centerScreenInBodyBg = function() {
  if (this.de_mayflower_royaleMvp_base_Website_bgBody.width > this.de_mayflower_royaleMvp_base_Website_bgScreen.width) {
    this.de_mayflower_royaleMvp_base_Website_bgScreen.x = ((this.de_mayflower_royaleMvp_base_Website_bgBody.width - this.de_mayflower_royaleMvp_base_Website_bgScreen.width) / 2);
  } else {
    this.de_mayflower_royaleMvp_base_Website_bgScreen.x = 0;
  }
  if (this.de_mayflower_royaleMvp_base_Website_bgBody.height > this.de_mayflower_royaleMvp_base_Website_bgScreen.height) {
    this.de_mayflower_royaleMvp_base_Website_bgScreen.y = ((this.de_mayflower_royaleMvp_base_Website_bgBody.height - this.de_mayflower_royaleMvp_base_Website_bgScreen.height) / 2);
  } else {
    this.de_mayflower_royaleMvp_base_Website_bgScreen.y = 0;
  }
};


/***************************************************************************************************************
 *   Sets up all content images for the website.
 *
 *   @asparam images All content images to assign to the website.
 * @export
 * @param {Array} images
 */
de.mayflower.royaleMvp.base.Website.prototype.setupGalleryImages = function(images) {
  this.de_mayflower_royaleMvp_base_Website_galleryImages = images;
  var /** @type {number} */ currentX = 0;
  for (var /** @type {number} */ i = 0; i < this.de_mayflower_royaleMvp_base_Website_galleryImages.length; ++i) {
    this.de_mayflower_royaleMvp_base_Website_galleryImages[i].visible = true;
    this.de_mayflower_royaleMvp_base_Website_galleryImages[i].setStyle("opacity", "0.0");
    this.de_mayflower_royaleMvp_base_Website_galleryImages[i].width = (de.mayflower.royaleMvp.base.Setting.OFFSET_GALLERY_HEIGHT * this.de_mayflower_royaleMvp_base_Website_galleryImages[i].width / this.de_mayflower_royaleMvp_base_Website_galleryImages[i].height);
    this.de_mayflower_royaleMvp_base_Website_galleryImages[i].height = de.mayflower.royaleMvp.base.Setting.OFFSET_GALLERY_HEIGHT;
    this.de_mayflower_royaleMvp_base_Website_galleryImages[i].x = currentX;
    this.de_mayflower_royaleMvp_base_Website_galleryImages[i].y = de.mayflower.royaleMvp.base.Setting.OFFSET_GALLERY_IMAGES_Y;
    currentX += Number(this.de_mayflower_royaleMvp_base_Website_galleryImages[i].width);
  }
  this.de_mayflower_royaleMvp_base_Website_galleryTotalWidth = currentX;
};


/***************************************************************************************************************
 *   Initializes all elements for the website.
 *
 *   @asparam imageMenuPlaceholder The image to use as the menu placeholder.
 *   @asparam imageHeaderLogo      The image to use as the header logo.
 * @export
 * @param {mx.controls.Image} imageMenuPlaceholder
 * @param {mx.controls.Image} imageHeaderLogo
 */
de.mayflower.royaleMvp.base.Website.prototype.initWebsiteElements = function(imageMenuPlaceholder, imageHeaderLogo) {
  this.de_mayflower_royaleMvp_base_Website_menuPlaceholder = imageMenuPlaceholder;
  this.de_mayflower_royaleMvp_base_Website_headerLogo = imageHeaderLogo;
  this.de_mayflower_royaleMvp_base_Website_menuPlaceholder.visible = true;
  this.de_mayflower_royaleMvp_base_Website_menuPlaceholder.setX(0);
  this.de_mayflower_royaleMvp_base_Website_menuPlaceholder.setY(de.mayflower.royaleMvp.base.Setting.SCREEN_HEIGHT - this.de_mayflower_royaleMvp_base_Website_menuPlaceholder.height);
  this.de_mayflower_royaleMvp_base_Website_menuPlaceholder.setStyle("opacity", "0.0");
  this.de_mayflower_royaleMvp_base_Website_headerLogo.visible = true;
  this.de_mayflower_royaleMvp_base_Website_headerLogo.setX(de.mayflower.royaleMvp.base.Setting.OFFSET_HEADER_LOGO_X);
  this.de_mayflower_royaleMvp_base_Website_headerLogo.setY(de.mayflower.royaleMvp.base.Setting.OFFSET_HEADER_LOGO_Y);
  this.de_mayflower_royaleMvp_base_Website_headerLogo.setStyle("opacity", "0.0");
  this.de_mayflower_royaleMvp_base_Website_scrollLane = de.mayflower.royaleMvp.ui.UIComponentFacility.createFilledRect(de.mayflower.royaleMvp.base.Setting.SCREEN_WIDTH + "px", de.mayflower.royaleMvp.base.Setting.OFFSET_SCROLL_LANE_HEIGHT + "px", de.mayflower.royaleMvp.base.Setting.COLOR_SCROLL_LANE);
  this.de_mayflower_royaleMvp_base_Website_scrollLane.setY(de.mayflower.royaleMvp.base.Setting.OFFSET_GALLERY_IMAGES_Y + de.mayflower.royaleMvp.base.Setting.OFFSET_GALLERY_HEIGHT);
  this.de_mayflower_royaleMvp_base_Website_scrollLane.setStyle("opacity", "0.0");
  this.de_mayflower_royaleMvp_base_Website_scrollKnob = de.mayflower.royaleMvp.ui.UIComponentFacility.createFilledRect(de.mayflower.royaleMvp.base.Setting.OFFSET_SCROLL_KNOB_WIDTH + "px", de.mayflower.royaleMvp.base.Setting.OFFSET_SCROLL_LANE_HEIGHT + "px", de.mayflower.royaleMvp.base.Setting.COLOR_SCROLL_KNOB);
  this.de_mayflower_royaleMvp_base_Website_scrollKnob.setY(de.mayflower.royaleMvp.base.Setting.OFFSET_GALLERY_IMAGES_Y + de.mayflower.royaleMvp.base.Setting.OFFSET_GALLERY_HEIGHT);
  this.de_mayflower_royaleMvp_base_Website_scrollKnob.setStyle("opacity", "0.0");
  de.mayflower.royaleMvp.base.App.addElement(this.getBgScreen(), this.de_mayflower_royaleMvp_base_Website_scrollLane);
  de.mayflower.royaleMvp.base.App.addElement(this.getBgScreen(), this.de_mayflower_royaleMvp_base_Website_scrollKnob);
};


/***************************************************************************************************************
 *   Sets the opacity for all elements of the website.
 *
 *   @asparam opacity The opacity to set.
 * @export
 * @param {string} opacity
 */
de.mayflower.royaleMvp.base.Website.prototype.setContentOpacity = function(opacity) {
  this.de_mayflower_royaleMvp_base_Website_menuPlaceholder.setStyle("opacity", opacity);
  this.de_mayflower_royaleMvp_base_Website_headerLogo.setStyle("opacity", opacity);
  this.de_mayflower_royaleMvp_base_Website_scrollLane.setStyle("opacity", opacity);
  this.de_mayflower_royaleMvp_base_Website_scrollKnob.setStyle("opacity", opacity);
  for (var /** @type {number} */ i = 0; i < this.de_mayflower_royaleMvp_base_Website_galleryImages.length; ++i) {
    this.de_mayflower_royaleMvp_base_Website_galleryImages[i].setStyle("opacity", opacity);
  }
};


/***************************************************************************************************************
 *   Animates the gallery for one tick of the game loop.
 * @export
 */
de.mayflower.royaleMvp.base.Website.prototype.animateGallery = function() {
  
/**
 * @const
 * @type {number}
 */
var MAX_X = this.de_mayflower_royaleMvp_base_Website_galleryTotalWidth - de.mayflower.royaleMvp.base.Setting.SCREEN_WIDTH;
  this.de_mayflower_royaleMvp_base_Website_galleryAnimationX += de.mayflower.royaleMvp.base.Setting.OFFSET_GALLERY_SPEED_X;
  if (this.de_mayflower_royaleMvp_base_Website_galleryAnimationX > MAX_X) {
    this.de_mayflower_royaleMvp_base_Website_galleryAnimationX = MAX_X;
  }
  var /** @type {number} */ currentX = -this.de_mayflower_royaleMvp_base_Website_galleryAnimationX;
  for (var /** @type {number} */ j = 0; j < this.de_mayflower_royaleMvp_base_Website_galleryImages.length; ++j) {
    this.de_mayflower_royaleMvp_base_Website_galleryImages[j].x = currentX;
    currentX += Number(this.de_mayflower_royaleMvp_base_Website_galleryImages[j].width);
  }
  var /** @type {number} */ scrollKnobX = (this.de_mayflower_royaleMvp_base_Website_galleryAnimationX * (de.mayflower.royaleMvp.base.Setting.SCREEN_WIDTH - de.mayflower.royaleMvp.base.Setting.OFFSET_SCROLL_KNOB_WIDTH) / MAX_X);
  this.de_mayflower_royaleMvp_base_Website_scrollKnob.setX(scrollKnobX);
};


/***************************************************************************************************************
 *   Sets the opacity for the screen background.
 *
 *   @asparam opacity The opacity to set as a String.
 * @export
 * @param {string} opacity
 */
de.mayflower.royaleMvp.base.Website.prototype.setScreenOpacity = function(opacity) {
  this.de_mayflower_royaleMvp_base_Website_bgScreen.setStyle("opacity", opacity);
};


/***************************************************************************************************************
 *   Delivers the screen background.
 *
 *   @asreturn The screen bg.
 * @export
 * @return {mx.core.UIComponent}
 */
de.mayflower.royaleMvp.base.Website.prototype.getBgScreen = function() {
  return this.de_mayflower_royaleMvp_base_Website_bgScreen;
};


/***************************************************************************************************************
 *   Sets the document title.
 *
 *   @asparam title The web page title to set.
 * @export
 * @param {string} title
 */
de.mayflower.royaleMvp.base.Website.prototype.setTitle = function(title) {
  document.title = title;
};


/***************************************************************************************************************
 *   Sets the bg color for the document body.
 *
 *   @asparam color CSS-Color value to assign.
 * @export
 * @param {string} color
 */
de.mayflower.royaleMvp.base.Website.prototype.setBodyBgColor = function(color) {
  document.body.style.background = color;
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
de.mayflower.royaleMvp.base.Website.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'Website', qName: 'de.mayflower.royaleMvp.base.Website', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
de.mayflower.royaleMvp.base.Website.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {return {};},
    methods: function () {
      return {
        'createBgBody': { type: 'void', declaredBy: 'de.mayflower.royaleMvp.base.Website', parameters: function () { return [ { index: 1, type: '*', optional: false } ]; }},
        'createBgScreen': { type: 'void', declaredBy: 'de.mayflower.royaleMvp.base.Website'},
        'centerScreenInBodyBg': { type: 'void', declaredBy: 'de.mayflower.royaleMvp.base.Website'},
        'setupGalleryImages': { type: 'void', declaredBy: 'de.mayflower.royaleMvp.base.Website', parameters: function () { return [ { index: 1, type: 'Array', optional: false } ]; }},
        'initWebsiteElements': { type: 'void', declaredBy: 'de.mayflower.royaleMvp.base.Website', parameters: function () { return [ { index: 1, type: 'mx.controls.Image', optional: false },{ index: 2, type: 'mx.controls.Image', optional: false } ]; }},
        'setContentOpacity': { type: 'void', declaredBy: 'de.mayflower.royaleMvp.base.Website', parameters: function () { return [ { index: 1, type: 'String', optional: false } ]; }},
        'animateGallery': { type: 'void', declaredBy: 'de.mayflower.royaleMvp.base.Website'},
        'setScreenOpacity': { type: 'void', declaredBy: 'de.mayflower.royaleMvp.base.Website', parameters: function () { return [ { index: 1, type: 'String', optional: false } ]; }},
        'getBgScreen': { type: 'mx.core.UIComponent', declaredBy: 'de.mayflower.royaleMvp.base.Website'},
        'setTitle': { type: 'void', declaredBy: 'de.mayflower.royaleMvp.base.Website', parameters: function () { return [ { index: 1, type: 'String', optional: false } ]; }},
        'setBodyBgColor': { type: 'void', declaredBy: 'de.mayflower.royaleMvp.base.Website', parameters: function () { return [ { index: 1, type: 'String', optional: false } ]; }}
      };
    }
  };
};
/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.base.Website.prototype.ROYALE_REFLECTION_INFO.compileFlags = 9;

//# sourceMappingURL=./Website.js.map
