/**
 * Generated by Apache Royale Compiler from Mg.mxml
 * Mg
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('Mg');
goog.require('de.mayflower.royaleMvp.base.App');
goog.require('mx.styles.StyleManagerImpl');
goog.require('org.apache.royale.core.ItemRendererClassFactory');
goog.require('org.apache.royale.core.StatesWithTransitionsImpl');
goog.require('org.apache.royale.events.Event');
goog.require('org.apache.royale.express.Application');
goog.require('org.apache.royale.express.beads.models.DataGridModel');
goog.require('org.apache.royale.html.beads.DataItemRendererFactoryForCollectionView');
goog.require('org.apache.royale.html.beads.ImageView');
goog.require('org.apache.royale.html.beads.ListView');
goog.require('org.apache.royale.html.beads.controllers.ItemRendererMouseController');
goog.require('org.apache.royale.html.beads.controllers.ItemRendererMouseController');
goog.require('org.apache.royale.html.beads.controllers.ListSingleSelectionMouseController');
goog.require('org.apache.royale.html.beads.layouts.VerticalLayout');
goog.require('org.apache.royale.html.beads.models.ImageModel');
goog.require('org.apache.royale.html.beads.models.ViewportModel');
goog.require('org.apache.royale.html.supportClasses.StringItemRenderer');
goog.require('org.apache.royale.html.supportClasses.Viewport');
goog.require('org.apache.royale.utils.EffectTimer');
goog.require('org.apache.royale.express.Application');
goog.require('org.apache.royale.reflection.getDefinitionByName');
goog.require('de.mayflower.royaleMvp.base.State');
goog.require('mx.resources.ResourceManagerImpl');
goog.require('mx.core.FlexGlobals');
goog.require('org.apache.royale.reflection.nativejs.AS3String');
goog.require('org.apache.royale.states.SetEventHandler');
goog.require('org.apache.royale.core.IStyleObject');
goog.require('org.apache.royale.utils.MXMLDataInterpreter');
goog.require('org.apache.royale.states.AddItems');
goog.require('mx.styles.StyleManager');
goog.require('org.apache.royale.reflection.nativejs.AS3Array');
goog.require('org.apache.royale.events.ItemClickedEvent');
goog.require('org.apache.royale.html.util.getLabelFromData');
goog.require('mx.core.UITextFormat');
goog.require('org.apache.royale.core.IMeasurementBead');
goog.require('org.apache.royale.reflection.ExtraData');
goog.require('org.apache.royale.events.MouseEvent');
goog.require('org.apache.royale.utils.Endian');
goog.require('org.apache.royale.states.SetProperty');
goog.require('org.apache.royale.utils.LocaleUtils');
goog.require('org.apache.royale.reflection.nativejs.AS3Number');
goog.require('mx.controls.beads.ToolTipBead');
goog.require('org.apache.royale.html.util.addElementToWrapper');
goog.require('org.apache.royale.core.styles.BorderStyles');
goog.require('mx.core.Singleton');
goog.require('de.mayflower.royaleMvp.base.Setting');
goog.require('mx.managers.IFocusManagerComponent');
goog.require('mx.events.PropertyChangeEventKind');
goog.require('mx.managers.IFocusManager');
goog.require('de.mayflower.royaleMvp.base.Preloader');
goog.require('mx.styles.CSSStyleDeclaration');
goog.require('org.apache.royale.utils.CSSUtils');
goog.require('mx.validators.ValidationResult');
goog.require('org.apache.royale.binding.SimpleBinding');
goog.require('org.apache.royale.geom.Point');
goog.require('mx.resources.LocaleSorter');
goog.require('org.apache.royale.binding.ConstantBinding');
goog.require('org.apache.royale.events.ItemAddedEvent');
goog.require('mx.managers.SystemManagerGlobals');
goog.require('mx.utils.StringUtil');
goog.require('de.mayflower.royaleMvp.io.ImageSystem');
goog.require('org.apache.royale.effects.Effect');
goog.require('mx.events.KeyboardEvent');
goog.require('org.apache.royale.reflection.nativejs.AS3int');
goog.require('org.apache.royale.events.getTargetWrapper');
goog.require('mx.resources.ResourceManager');
goog.require('org.apache.royale.core.IApplicationView');
goog.require('org.apache.royale.debugging.assertType');
goog.require('mx.core.UITextField');
goog.require('mx.managers.SystemManager');
goog.require('de.mayflower.royaleMvp.io.ImageResource');
goog.require('mx.display.Graphics');
goog.require('org.apache.royale.geom.Size');
goog.require('QName');
goog.require('org.apache.royale.states.State');
goog.require('org.apache.royale.events.ValueChangeEvent');
goog.require('org.apache.royale.utils.BinaryData');
goog.require('mx.managers.IFocusManagerContainer');
goog.require('org.apache.royale.core.TextLineMetrics');
goog.require('org.apache.royale.utils.net.IDataOutput');
goog.require('org.apache.royale.core.IMXMLDocument');
goog.require('org.apache.royale.core.ClassFactory');
goog.require('mx.core.LayoutElementUIComponentUtils');
goog.require('org.apache.royale.debugging.assert');
goog.require('org.apache.royale.utils.StringUtil');
goog.require('org.apache.royale.html.beads.DisableBead');
goog.require('org.apache.royale.events.CollectionEvent');
goog.require('org.apache.royale.reflection.nativejs.AS3Vector');
goog.require('org.apache.royale.core.ILayoutParent');
goog.require('org.apache.royale.geom.Rectangle');
goog.require('org.apache.royale.core.AllCSSValuesImpl');
goog.require('org.apache.royale.utils.StringTrimmer');
goog.require('mx.modules.IModuleInfo');
goog.require('org.apache.royale.html.beads.DisabledAlphaBead');
goog.require('org.apache.royale.core.IContainer');
goog.require('org.apache.royale.utils.UIUtils');
goog.require('mx.events.ValidationResultEvent');
goog.require('org.apache.royale.core.layout.MarginData');
goog.require('org.apache.royale.core.SimpleCSSStyles');
goog.require('org.apache.royale.states.Transition');
goog.require('de.mayflower.royaleMvp.base.Website');
goog.require('org.apache.royale.core.CallLaterBead');
goog.require('org.apache.royale.reflection.nativejs.AS3uint');
goog.require('mx.managers.ICursorManager');
goog.require('org.apache.royale.collections.ArrayList');
goog.require('org.apache.royale.binding.ApplicationDataBinding');
goog.require('mx.core.mx_internal');
goog.require('org.apache.royale.core.IListPresentationModel');
goog.require('de.mayflower.royaleMvp.ui.UIComponentFacility');
goog.require('mx.core.FlexCSSStyles');
goog.require('mx.controls.Image');
goog.require('org.apache.royale.states.ItemAndDescriptor');
goog.require('org.apache.royale.binding.GenericBinding');
goog.require('org.apache.royale.utils.PointUtils');
goog.require('org.apache.royale.utils.net.IDataInput');
goog.require('org.apache.royale.html.supportClasses.ContainerContentArea');
goog.require('org.apache.royale.utils.loadBeadFromValuesManager');
goog.require('mx.geom.Matrix');
goog.require('org.apache.royale.binding.PropertyWatcher');
goog.require('mx.core.ITextFieldFactory');
goog.require('mx.resources.ResourceBundle');
goog.require('org.apache.royale.core.IItemRendererProvider');
goog.require('org.apache.royale.events.ItemRemovedEvent');
goog.require('org.apache.royale.html.ToolTip');
goog.require('org.apache.royale.debugging.throwError');
goog.require('org.apache.royale.events.ValueEvent');
goog.require('org.apache.royale.conversions.createEventInit');
goog.require('org.apache.royale.core.layout.LayoutData');
goog.require('org.apache.royale.utils.StringPadder');
goog.require('XMLList');
goog.require('org.apache.royale.reflection.nativejs.AS3Boolean');
goog.require('org.apache.royale.utils.Timer');
goog.require('XML');
goog.require('mx.events.PropertyChangeEvent');
goog.require('mx.events.FlexEvent');
/* Royale Dependency List: de.mayflower.royaleMvp.base.App,org.apache.royale.events.Event,mx.styles.StyleManagerImpl,org.apache.royale.html.beads.controllers.ItemRendererMouseController,org.apache.royale.html.beads.controllers.ItemRendererMouseController,org.apache.royale.utils.EffectTimer,org.apache.royale.core.StatesWithTransitionsImpl,org.apache.royale.html.beads.ListView,org.apache.royale.html.supportClasses.StringItemRenderer,org.apache.royale.html.supportClasses.Viewport,org.apache.royale.html.beads.layouts.VerticalLayout,org.apache.royale.express.beads.models.DataGridModel,org.apache.royale.html.beads.controllers.ListSingleSelectionMouseController,org.apache.royale.core.ItemRendererClassFactory,org.apache.royale.html.beads.models.ViewportModel,org.apache.royale.html.beads.DataItemRendererFactoryForCollectionView,org.apache.royale.html.beads.ImageView,org.apache.royale.html.beads.models.ImageModel*/

goog.require('org.apache.royale.express.Application');



/**
 * @constructor
 * @extends {org.apache.royale.express.Application}
 */
Mg = function() {
  Mg.base(this, 'constructor');
  
  /**
   * @private
   * @type {Array}
   */
  this.mxmldd;
  
  /**
   * @private
   * @type {Array}
   */
  this.mxmldp;

  this.generateMXMLAttributes
  ([0,
0,
1,
'applicationComplete',
this.$EH0
  ]);
  
};
goog.inherits(Mg, org.apache.royale.express.Application);


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('Mg', Mg);



/***************************************************************************************************************
 *   Being invoked when the application has completed loading.
 * @private
 */
Mg.prototype.Mg_onApplicationComplete = function() {
  var /** @type {de.mayflower.royaleMvp.base.App} */ mgApp = new de.mayflower.royaleMvp.base.App();
  mgApp.start(this);
};


/**
 * @export
 * @param {org.apache.royale.events.Event} event
 */
Mg.prototype.$EH0 = function(event)
{
  this.Mg_onApplicationComplete();
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
Mg.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'Mg', qName: 'Mg', kind: 'class'  }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
Mg.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {return {};},
    methods: function () {
      return {
        'Mg': { type: '', declaredBy: 'Mg'}
      };
    }
  };
};
/**
 * @export
 * @const
 * @type {number}
 */
Mg.prototype.ROYALE_REFLECTION_INFO.compileFlags = 9;



//# sourceMappingURL=./Mg.js.map


Mg.prototype.info = function() {
  return { "mixins": [mx.styles.StyleManagerImpl],
"compiledLocales": ["en_US"]}};


Mg.prototype.cssData = [0,
1,
".Application *",
function() {this["WebkitBoxSizing"] = "border-box";
this["boxSizing"] = "border-box";
this["MozBoxSizing"] = "border-box"},
0,
1,
".royale *",
function() {this["WebkitBoxSizing"] = "border-box";
this["boxSizing"] = "border-box";
this["MozBoxSizing"] = "border-box"},
0,
1,
".royale *:before",
function() {this["WebkitBoxSizing"] = "border-box";
this["boxSizing"] = "border-box";
this["MozBoxSizing"] = "border-box"},
0,
1,
".royale *:after",
function() {this["WebkitBoxSizing"] = "border-box";
this["boxSizing"] = "border-box";
this["MozBoxSizing"] = "border-box"},
0,
1,
"org.apache.royale.core.Application",
function() {this["padding"] = 0.0;
this["margin"] = 0.0},
0,
1,
"org.apache.royale.html.supportClasses.DataItemRenderer",
function() {this["iBeadController"] = org.apache.royale.html.beads.controllers.ItemRendererMouseController},
0,
1,
"org.apache.royale.html.supportClasses.StringItemRenderer",
function() {this["cursor"] = "pointer";
this["paddingBottom"] = 4.0;
this["flexGrow"] = 1.0;
this["fontFamily"] = "sans-serif";
this["flexShrink"] = 0.0;
this["iBeadController"] = org.apache.royale.html.beads.controllers.ItemRendererMouseController;
this["fontSize"] = 12.0;
this["paddingTop"] = 4.0},
0,
1,
"org.apache.royale.html.ToolTip",
function() {this["backgroundColor"] = 16777164;
this["paddingRight"] = 3.0;
this["paddingLeft"] = 3.0},
0,
1,
"global",
function() {this["iEffectTimer"] = org.apache.royale.utils.EffectTimer;
this["verticalAlign"] = "top";
this["padding"] = 0.0;
this["horizontalGap"] = 8.0;
this["errorColor"] = 13510953;
this["horizontalAlign"] = "left";
this["whiteSpaceCollapse"] = "collapse";
this["effectTimerInterval"] = 10.0;
this["verticalGap"] = 6.0;
this["iStatesImpl"] = org.apache.royale.core.StatesWithTransitionsImpl},
0,
1,
"org.apache.royale.express.Application",
function() {this["padding"] = 0.0;
this["margin"] = 0.0},
0,
1,
".DataGridColumnList",
function() {this["iBeadView"] = org.apache.royale.html.beads.ListView;
this["iItemRenderer"] = org.apache.royale.html.supportClasses.StringItemRenderer;
this["iViewport"] = org.apache.royale.html.supportClasses.Viewport;
this["backgroundColor"] = 16777215;
this["iBeadLayout"] = org.apache.royale.html.beads.layouts.VerticalLayout;
this["iBeadModel"] = org.apache.royale.express.beads.models.DataGridModel;
this["iBeadController"] = org.apache.royale.html.beads.controllers.ListSingleSelectionMouseController;
this["iItemRendererClassFactory"] = org.apache.royale.core.ItemRendererClassFactory;
this["iViewportModel"] = org.apache.royale.html.beads.models.ViewportModel;
this["iDataProviderItemRendererMapper"] = org.apache.royale.html.beads.DataItemRendererFactoryForCollectionView;
this["borderStyle"] = "none"},
0,
1,
".SliderTrack",
function() {this["position"] = "absolute"},
0,
1,
".SliderThumb",
function() {this["position"] = "absolute"},
0,
1,
"*",
function() {this["fontFamily"] = "Verdana";
this["fontSize"] = 12.0},
0,
1,
"mx.controls.Image",
function() {this["iBeadView"] = org.apache.royale.html.beads.ImageView;
this["iBeadModel"] = org.apache.royale.html.beads.models.ImageModel},
0,
1,
"Panel .TitleBar",
function() {this["borderBottom"] = [1.0, "solid", 3355443]},
0,
1,
".PanelContent",
function() {this["backgroundColor"] = 16777215},
0,
1,
".verticalAxisStyle",
function() {this["minorTickLength"] = 2.0;
this["tickLength"] = 5.0;
this["minorTickPlacement"] = "outside"},
0,
1,
".blockNumericAxis",
function() {this["minorTickLength"] = 0.0;
this["tickLength"] = 8.0;
this["minorTickPlacement"] = "cross"},
0,
1,
".linedNumericAxis",
function() {this["minorTickLength"] = 4.0;
this["tickLength"] = 8.0;
this["minorTickPlacement"] = "outside"},
0,
1,
".dashedNumericAxis",
function() {this["minorTickLength"] = 4.0;
this["tickLength"] = 8.0;
this["showLine"] = false;
this["minorTickPlacement"] = "outside"},
0,
1,
".blockCategoryAxis",
function() {this["minorTickLength"] = 0.0;
this["tickPlacement"] = "cross";
this["tickLength"] = 0.0;
this["minorTickPlacement"] = "none"},
0,
1,
".hangingCategoryAxis",
function() {this["minorTickLength"] = 0.0;
this["tickLength"] = 4.0;
this["minorTickPlacement"] = "cross"},
0,
1,
".dashedCategoryAxis",
function() {this["tickPlacement"] = "cross";
this["tickLength"] = 0.0;
this["minorTickPlacement"] = "none"},
0,
1,
".horizontalGridLines",
function() {this["verticalShowOrigin"] = true;
this["verticalTickAligned"] = true;
this["gridDirection"] = "vertical";
this["horizontalShowOrigin"] = false;
this["horizontalTickAligned"] = true},
0,
1,
".bothGridLines",
function() {this["verticalShowOrigin"] = true;
this["verticalTickAligned"] = true;
this["gridDirection"] = "both";
this["horizontalShowOrigin"] = true;
this["horizontalTickAligned"] = true},
0,
1,
"org.apache.royale.html.Label",
function() {this["fontFamily"] = "sans-serif";
this["fontSize"] = 12.0}];
