/**
 * Generated by Apache Royale Compiler from mx/managers/IFocusManager.as
 * mx.managers.IFocusManager
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('mx.managers.IFocusManager');
/* Royale Dependency List: mx.managers.IFocusManagerComponent,XML*/

goog.require('org.apache.royale.events.IEventDispatcher');



/**
 * @interface
 * @extends {org.apache.royale.events.IEventDispatcher}
 */
mx.managers.IFocusManager = function() {
};


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('mx.managers.IFocusManager', mx.managers.IFocusManager);
/**
 * @export
 * @param {boolean=} backward
 * @return {mx.managers.IFocusManagerComponent}
 */
mx.managers.IFocusManager.prototype.getNextFocusManagerComponent = function(backward) {
};
/**
 * @export
 * @return {mx.managers.IFocusManagerComponent}
 */
mx.managers.IFocusManager.prototype.getFocus = function() {
};
/**
 * @export
 * @param {mx.managers.IFocusManagerComponent} o
 */
mx.managers.IFocusManager.prototype.setFocus = function(o) {
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
mx.managers.IFocusManager.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'IFocusManager', qName: 'mx.managers.IFocusManager', kind: 'interface' }], interfaces: [org.apache.royale.events.IEventDispatcher] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
mx.managers.IFocusManager.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    accessors: function () {return {};},
    methods: function () {
      return {
        'getNextFocusManagerComponent': { type: 'mx.managers.IFocusManagerComponent', declaredBy: 'mx.managers.IFocusManager', parameters: function () { return [ { index: 1, type: 'Boolean', optional: true } ]; }},
        'getFocus': { type: 'mx.managers.IFocusManagerComponent', declaredBy: 'mx.managers.IFocusManager'},
        'setFocus': { type: 'void', declaredBy: 'mx.managers.IFocusManager', parameters: function () { return [ { index: 1, type: 'mx.managers.IFocusManagerComponent', optional: false } ]; }}
      };
    }
  };
};
/**
 * @export
 * @const
 * @type {number}
 */
mx.managers.IFocusManager.prototype.ROYALE_REFLECTION_INFO.compileFlags = 26;
