/**
 * Generated by Apache Royale Compiler from org/apache/royale/express/Application.as
 * org.apache.royale.express.Application
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('org.apache.royale.express.Application');
/* Royale Dependency List: org.apache.royale.binding.ApplicationDataBinding,org.apache.royale.core.AllCSSValuesImpl*/

goog.require('org.apache.royale.core.Application');



/**
 * @constructor
 * @extends {org.apache.royale.core.Application}
 */
org.apache.royale.express.Application = function() {
  org.apache.royale.express.Application.base(this, 'constructor');
  this.valuesImpl = new org.apache.royale.core.AllCSSValuesImpl();
  this.addBead(new org.apache.royale.binding.ApplicationDataBinding());
};
goog.inherits(org.apache.royale.express.Application, org.apache.royale.core.Application);


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('org.apache.royale.express.Application', org.apache.royale.express.Application);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.express.Application.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'Application', qName: 'org.apache.royale.express.Application', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.express.Application.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {return {};},
    methods: function () {
      return {
        'Application': { type: '', declaredBy: 'org.apache.royale.express.Application'}
      };
    }
  };
};
/**
 * @export
 * @const
 * @type {number}
 */
org.apache.royale.express.Application.prototype.ROYALE_REFLECTION_INFO.compileFlags = 10;
