/**
 * Generated by Apache Royale Compiler from de/mayflower/royaleMvp/ui/UIComponentFacility.as
 * de.mayflower.royaleMvp.ui.UIComponentFacility
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('de.mayflower.royaleMvp.ui.UIComponentFacility');
/* Royale Dependency List: mx.core.UIComponent*/




/**
 * @constructor
 */
de.mayflower.royaleMvp.ui.UIComponentFacility = function() {
};


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('de.mayflower.royaleMvp.ui.UIComponentFacility', de.mayflower.royaleMvp.ui.UIComponentFacility);


/***************************************************************************************************************
 *   Creates a filled rectangle.
 *
 *   @asparam width  The dimension X of the rectangle.
 *   @asparam height The dimension X of the rectangle.
 *   @asparam color  The color to fill the rectangle with.
 *
 *   @asreturn The created rectangle.
 * @export
 * @param {string} width
 * @param {string} height
 * @param {string} color
 * @return {mx.core.UIComponent}
 */
de.mayflower.royaleMvp.ui.UIComponentFacility.createFilledRect = function(width, height, color) {
  var /** @type {mx.core.UIComponent} */ rect = new mx.core.UIComponent();
  rect.visible = true;
  rect.setStyle("width", width);
  rect.setStyle("height", height);
  rect.setStyle("background", color);
  return rect;
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
de.mayflower.royaleMvp.ui.UIComponentFacility.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'UIComponentFacility', qName: 'de.mayflower.royaleMvp.ui.UIComponentFacility', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
de.mayflower.royaleMvp.ui.UIComponentFacility.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {return {};},
    methods: function () {
      return {
        '|createFilledRect': { type: 'mx.core.UIComponent', declaredBy: 'de.mayflower.royaleMvp.ui.UIComponentFacility', parameters: function () { return [ { index: 1, type: 'String', optional: false },{ index: 2, type: 'String', optional: false },{ index: 3, type: 'String', optional: false } ]; }}
      };
    }
  };
};
/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.ui.UIComponentFacility.prototype.ROYALE_REFLECTION_INFO.compileFlags = 9;
/**
 * Provide reflection support for distinguishing dynamic fields on class object (static)
 * @export
 * @const
 * @type {Array<string>}
 */
de.mayflower.royaleMvp.ui.UIComponentFacility.prototype.ROYALE_REFLECTION_INFO.statics = Object.keys(de.mayflower.royaleMvp.ui.UIComponentFacility);

//# sourceMappingURL=./UIComponentFacility.js.map
