/**
 * Generated by Apache Royale Compiler from org/apache/royale/utils/LocaleUtils.as
 * org.apache.royale.utils.LocaleUtils
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('org.apache.royale.utils.LocaleUtils');
/* Royale Dependency List: */



/**
 * @constructor
 */
org.apache.royale.utils.LocaleUtils = function() {
};


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('org.apache.royale.utils.LocaleUtils', org.apache.royale.utils.LocaleUtils);


/**
 * Gets the locale of the operating system.
 * @export
 * @return {string}
 */
org.apache.royale.utils.LocaleUtils.getLocale = function() {
  
  if (!org.apache.royale.utils.LocaleUtils._localeName) {
    org.apache.royale.utils.LocaleUtils._localeName = navigator.language;
  }
  return org.apache.royale.utils.LocaleUtils._localeName;
};


/**
 * @private
 * @type {string}
 */
org.apache.royale.utils.LocaleUtils._localeName;


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.utils.LocaleUtils.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'LocaleUtils', qName: 'org.apache.royale.utils.LocaleUtils', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.utils.LocaleUtils.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {return {};},
    methods: function () {
      return {
        'LocaleUtils': { type: '', declaredBy: 'org.apache.royale.utils.LocaleUtils'},
        '|getLocale': { type: 'String', declaredBy: 'org.apache.royale.utils.LocaleUtils'}
      };
    }
  };
};
/**
 * @export
 * @const
 * @type {number}
 */
org.apache.royale.utils.LocaleUtils.prototype.ROYALE_REFLECTION_INFO.compileFlags = 10;
