/**
 * Generated by Apache Royale Compiler from org/apache/royale/express/beads/models/DataGridModel.as
 * org.apache.royale.express.beads.models.DataGridModel
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('org.apache.royale.express.beads.models.DataGridModel');
/* Royale Dependency List: org.apache.royale.collections.ArrayList,org.apache.royale.utils.Language*/

goog.require('org.apache.royale.html.beads.models.DataGridCollectionViewModel');



/**
 * @constructor
 * @extends {org.apache.royale.html.beads.models.DataGridCollectionViewModel}
 */
org.apache.royale.express.beads.models.DataGridModel = function() {
  org.apache.royale.express.beads.models.DataGridModel.base(this, 'constructor');
};
goog.inherits(org.apache.royale.express.beads.models.DataGridModel, org.apache.royale.html.beads.models.DataGridCollectionViewModel);


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('org.apache.royale.express.beads.models.DataGridModel', org.apache.royale.express.beads.models.DataGridModel);


org.apache.royale.express.beads.models.DataGridModel.prototype.set__dataProvider = function(value) {
  if (org.apache.royale.utils.Language.is(value, Array)) {
    org.apache.royale.express.beads.models.DataGridModel.superClass_.set__dataProvider.apply(this, [ new org.apache.royale.collections.ArrayList(org.apache.royale.utils.Language.as(value, Array))] );
  } else {
    org.apache.royale.express.beads.models.DataGridModel.superClass_.set__dataProvider.apply(this, [ value] );
  }
};


Object.defineProperties(org.apache.royale.express.beads.models.DataGridModel.prototype, /** @lends {org.apache.royale.express.beads.models.DataGridModel.prototype} */ {
/**
  * @export
  * @type {Object} */
dataProvider: {
get: org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.get__dataProvider,
set: org.apache.royale.express.beads.models.DataGridModel.prototype.set__dataProvider}}
);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.express.beads.models.DataGridModel.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'DataGridModel', qName: 'org.apache.royale.express.beads.models.DataGridModel', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.express.beads.models.DataGridModel.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {
      return {
        'dataProvider': { type: 'Object', access: 'writeonly', declaredBy: 'org.apache.royale.express.beads.models.DataGridModel'}
      };
    },
    methods: function () {
      return {
        'DataGridModel': { type: '', declaredBy: 'org.apache.royale.express.beads.models.DataGridModel'}
      };
    }
  };
};
/**
 * @export
 * @const
 * @type {number}
 */
org.apache.royale.express.beads.models.DataGridModel.prototype.ROYALE_REFLECTION_INFO.compileFlags = 10;
