/**
 * Generated by Apache Royale Compiler from de/mayflower/royaleMvp/io/ImageResource.as
 * de.mayflower.royaleMvp.io.ImageResource
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('de.mayflower.royaleMvp.io.ImageResource');
/* Royale Dependency List: */



/**
 * @constructor
 */
de.mayflower.royaleMvp.io.ImageResource = function() {
};


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('de.mayflower.royaleMvp.io.ImageResource', de.mayflower.royaleMvp.io.ImageResource);


/**
 * @export
 * @const
 * @type {Array}
 */
de.mayflower.royaleMvp.io.ImageResource.IMAGES_PRELOADER = ["image_preloader/logoPreloader.png", "image_preloader/menu.png", "image_preloader/logoHeader.png"];


/**
 * @export
 * @const
 * @type {Array}
 */
de.mayflower.royaleMvp.io.ImageResource.IMAGES_GALLERY = ["image_cms/514.jpg", "image_cms/50.jpg", "image_cms/298.jpg", "image_cms/568.jpg", "image_cms/121.jpg", "image_cms/483.jpg", "image_cms/72.jpg", "image_cms/419.jpg", "image_cms/297.jpg", "image_cms/465.jpg", "image_cms/493.jpg", "image_cms/630.jpg", "image_cms/349.jpg", "image_cms/520.jpg", "image_cms/579.jpg", "image_cms/622.jpg", "image_cms/501.jpg", "image_cms/452.jpg", "image_cms/113.jpg", "image_cms/53.jpg", "image_cms/114.jpg", "image_cms/590.jpg", "image_cms/631.jpg", "image_cms/326.jpg", "image_cms/310.jpg", "image_cms/455.jpg", "image_cms/196.jpg", "image_cms/175.jpg", "image_cms/1.jpg", "image_cms/628.jpg", "image_cms/269.jpg", "image_cms/293.jpg", "image_cms/524.jpg", "image_cms/586.jpg"];


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
de.mayflower.royaleMvp.io.ImageResource.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'ImageResource', qName: 'de.mayflower.royaleMvp.io.ImageResource', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
de.mayflower.royaleMvp.io.ImageResource.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {return {};},
    methods: function () {return {};}
  };
};
/**
 * @export
 * @const
 * @type {number}
 */
de.mayflower.royaleMvp.io.ImageResource.prototype.ROYALE_REFLECTION_INFO.compileFlags = 9;
/**
 * Provide reflection support for distinguishing dynamic fields on class object (static)
 * @export
 * @const
 * @type {Array<string>}
 */
de.mayflower.royaleMvp.io.ImageResource.prototype.ROYALE_REFLECTION_INFO.statics = Object.keys(de.mayflower.royaleMvp.io.ImageResource);

//# sourceMappingURL=./ImageResource.js.map
